[tool.ruff]
line-length = 88           # same default as Black
indent-width = 2           # two-space indents
target-version = "py312"   # your Python version
lint.extend-select = ["I"]      # import-sorting rule
lint.ignore = [
  "E501",  # disable long-line warnings if you wrap manually
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"