name: Database update (automated)

on:
  workflow_dispatch: {}
  push:
    branches: ["test-workflows"]
  schedule:
    # Normal schedule: Runs once every day
    - cron: '0 0 */2 * *'
    # While backfilling: runs every four hours Mon–Sat (UTC)...
    # - cron: '0 */4 * * 1-6'
    # And on Sunday (UTC): every four hours, but NOT 12:00–18:00, to avoid conflicts with other workflow
    # - cron: '0 0-10/2,20,22 * * 0'
    # - cron: '0 0,4,8,20 * * 0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/New_York"
          timezoneMacos: "America/New_York"
          timezoneWindows: "Eastern Standard Time"

      - name: Set up Python 3.12.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install --deploy --dev

      - name: Ensure dev deps (pipenv)
        run: |
          pipenv sync --dev

      - name: Run unit + integration + smoke tests
        env:
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
        run: |
          # Show versions for debugging
          python -V
          pipenv --version
          pipenv run pytest -ra

      - name: Crawl users data
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
        run: cd data_processing && pipenv run python get_users.py

      - name: Crawl ratings data
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
        run: cd data_processing && pipenv run python get_ratings.py

      - name: Get movie data
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
        run: cd data_processing && pipenv run python get_movies.py
      
      - name: Prune inactive movie data from database
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
        run: cd data_processing && pipenv run python prune_inactive_movies.py
      
      - name: Consolidate/migrate data for any movies that now redirect to other pages
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
        run: cd data_processing && pipenv run python consolidate_redirects.py
