name: Data sample/live model update (automated)

on:
  workflow_dispatch: {}
  push:
    branches: ["test-workflows"]
  schedule:
    # runs once per week at noon (to not conflict with other workflow, which runs at midnight)
    - cron: '0 12 * * 0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/New_York"
          timezoneMacos: "America/New_York"
          timezoneWindows: "Eastern Standard Time"

      - name: Set up Python 3.12.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install --deploy --dev

      - name: Create new training data sample file
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL_CI }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
        run: cd data_processing && pipenv run python create_training_data.py
      
      - name: Evaluate model params and update prod params
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL_CI }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
        run: cd data_processing && pipenv run python evaluate_models.py

      - name: Build new cached models
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
        run: cd data_processing && pipenv run python build_model.py

      - name: Update last updated date
        run: cd data_processing && pipenv run python update_last_updated.py

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Automated update to sample data and live models (triggered from model-update.yml GitHub action)
          branch: main
          commit_options: '--no-verify --signoff'
          repository: .
