name: Refresh test user data

on:
  workflow_dispatch: {}
  push:
    branches: ["test-workflows"]
  schedule:
    # runs once every two months at 18:00 (to not conflict with other workflows, which runs at midnight/noon)
    - cron: '0 18 1 */2 *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/New_York"
          timezoneMacos: "America/New_York"
          timezoneWindows: "Eastern Standard Time"

      - name: Set up Python 3.12.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv install --deploy --dev

      - name: Update test user set
        env:
          CONNECTION_URL: ${{ secrets.CONNECTION_URL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
        run: cd data_processing && pipenv run python create_test_user_set.py

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Automated data update
          branch: main
          commit_options: '--no-verify --signoff'
          repository: .
